name: renovate-approve
run-name: CI for approving renovate PRs

on:
  push:
    branches:
      - "renovate/**"

jobs:
  autoapprove:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Approve PR
        run: |
          gh pr merge --auto
          gh pr review --approve
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}